### ISSUE TITLE
看了你写的项目，cell中buttonA和buttonB，点击事件（就包括了事件的传递）和响应链是不是重复用了，原因：本来uibutton就是继承uiResponder它自己有uiresponder扩展的方法；第二点：

### ISSUE THREAD

**Issue by manmanstrong** [objbee/casa-responder-chain#1]

**Comment by objbee** [comment]
1.UIButton 的点击事件只是为了触发 Responder Chain 传递，而且重点就是因为 UIButton 是继承 UIResonder 才可以调用 UIResponder+Router 里的方法，然后沿着 Responder Chain 逐步传递，这样的巧妙之处就是利用了 UIResponder 的这条 Responder Chain 实现对象交互，避免了原来利用 Delegate 层层传递或者公开属性等等较强耦合的对象交互。2.第二点？

**Comment by manmanstrong** [comment]
我的意思是unbutton的点击事件已经充当了和响应链一样向下一层父视图的传递的作用，如果没有数据向父视图的父视图传递的话，就没有必要在调一次响应链的方法感觉有点多余。就像demo中的BButton向vC中传递事件可以直接在点击事件中写要传的数据就可以了，代码如下
- (void)onClickBButton
{
    NSLog(@"%s", __func__);
    NSDictionary *dic = @{
                          @"TestData":@"testData",
                          
                          
                          };
    

    [self bEvent:dic];
}
- (void)bEvent:(NSDictionary *)userInfo
{
    NSMutableDictionary *mUserInfo = [NSMutableDictionary dictionaryWithDictionary:userInfo];
    [mUserInfo setValue:NSStringFromClass(self.class) forKey:@"eventClass"];
    
    // 如果需要让事件继续往上传递，则调用下面的语句
    [super routerEventWithName:ATableViewCellBEvent userInfo:mUserInfo];
}
不知道那样写是出于什么考虑的，我也是昨天看的casa的博客

**Comment by objbee** [comment]
1.你的意思没错，就 Demo 中 BButton 需传递的数据是可以直接写在点击事件中。2.之所以这样写，是为了简单演示文中说的结合 Strategy 和 Decorator 模式。
